// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'fa_card_posting_view_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FACardPostingViewModel _$FACardPostingViewModelFromJson(
        Map<String, dynamic> json) =>
    FACardPostingViewModel(
      json['id'] as int,
      json['cardNumber'] as String,
      json['commitDisplayCardNumberSave'] as bool,
      json['displayCardNumber'] as String,
      json['displayCardNumberSequence'] as int,
      json['displaySuffix'] as String,
      json['displayPrefix'] as String,
      json['description'] as String,
      json['serialNumber'] as String,
      json['responsibleEmployee'] as int?,
      json['isActive'] as bool,
      json['isBlocked'] as bool,
      json['purchasedDate'] == null
          ? null
          : DateTime.parse(json['purchasedDate'] as String),
      (json['purchaseQty'] as num).toDouble(),
      (json['purchaseCost'] as num).toDouble(),
      (json['openingBalance'] as num).toDouble(),
      json['previousFACode'] as String,
      json['fAClassCodeId'] as int?,
      json['fASubClassCodeId'] as int?,
      json['isUnderMaintenance'] as bool,
      json['fAModel'] as String,
      json['disableFALines'] as bool,
      json['isDisposed'] as bool,
      (json['bookValue'] as num).toDouble(),
      json['isDonated'] as bool,
      json['donorId'] as int?,
      json['fundType'] as String,
      json['description2'] as String,
      json['unit'] as String,
      json['unitValue'] as String,
      json['fATypeId'] as int?,
      json['majorLocationId'] as int?,
      json['fAComponentDetails'] as List<FAComponentViewModel>,
      json['fACardLineDetails'] as List<FACardLineViewModel>,
      json['fAResponsibleEmployeeDetails'] as List<FAResponsibleEmployeeViewModel>,
      json['fALocationDetails'] as List<FALocationViewModel>,
      json['fAMaintainanceInfoDetails'] as List<FAMaintainanceInfoViewModel>,
      json['fAGovernmentRenewalDetails'] as List<FAGovernmentRenewalViewModel>,
      json['fACardInsuranceDetails'] as List<FACardInsuranceViewModel>,
      json['fAComponent'],
      json['fACardLine'],
      json['fAResponsibleEmployee'],
      json['fALocation'],
      json['fAMaintainanceInfo'],
      json['fAGovernmentRenewal'],
      json['fACardInsurance'],
      json['fADisplayCardNumberCodeForEdit'],
    );

Map<String, dynamic> _$FACardPostingViewModelToJson(
        FACardPostingViewModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'cardNumber': instance.cardNumber,
      'commitDisplayCardNumberSave': instance.commitDisplayCardNumberSave,
      'displayCardNumber': instance.displayCardNumber,
      'displayCardNumberSequence': instance.displayCardNumberSequence,
      'displaySuffix': instance.displaySuffix,
      'displayPrefix': instance.displayPrefix,
      'description': instance.description,
      'serialNumber': instance.serialNumber,
      'responsibleEmployee': instance.responsibleEmployee,
      'isActive': instance.isActive,
      'isBlocked': instance.isBlocked,
      'purchasedDate': instance.purchasedDate?.toIso8601String(),
      'purchaseQty': instance.purchaseQty,
      'purchaseCost': instance.purchaseCost,
      'openingBalance': instance.openingBalance,
      'previousFACode': instance.previousFACode,
      'fAClassCodeId': instance.fAClassCodeId,
      'fASubClassCodeId': instance.fASubClassCodeId,
      'isUnderMaintenance': instance.isUnderMaintenance,
      'fAModel': instance.fAModel,
      'disableFALines': instance.disableFALines,
      'isDisposed': instance.isDisposed,
      'bookValue': instance.bookValue,
      'isDonated': instance.isDonated,
      'donorId': instance.donorId,
      'fundType': instance.fundType,
      'description2': instance.description2,
      'unit': instance.unit,
      'unitValue': instance.unitValue,
      'fATypeId': instance.fATypeId,
      'majorLocationId': instance.majorLocationId,
      'fAComponentDetails': instance.fAComponentDetails,
      'fACardLineDetails': instance.fACardLineDetails,
      'fAResponsibleEmployeeDetails': instance.fAResponsibleEmployeeDetails,
      'fALocationDetails': instance.fALocationDetails,
      'fAMaintainanceInfoDetails': instance.fAMaintainanceInfoDetails,
      'fAGovernmentRenewalDetails': instance.fAGovernmentRenewalDetails,
      'fACardInsuranceDetails': instance.fACardInsuranceDetails,
      'fAComponent': instance.fAComponent,
      'fACardLine': instance.fACardLine,
      'fAResponsibleEmployee': instance.fAResponsibleEmployee,
      'fALocation': instance.fALocation,
      'fAMaintainanceInfo': instance.fAMaintainanceInfo,
      'fAGovernmentRenewal': instance.fAGovernmentRenewal,
      'fACardInsurance': instance.fACardInsurance,
      'fADisplayCardNumberCodeForEdit': instance.fADisplayCardNumberCodeForEdit,
    };
